#include "mistercast/config.hpp"
#include <cstdlib>
#include <fstream>
#include <regex>
#include <sstream>
#include <system_error>
#include <unistd.h>

namespace mistercast {
std::filesystem::path configPath(){if(const char*x=std::getenv("XDG_CONFIG_HOME");x&&*x)return std::filesystem::path(x)/"mistercast/config.json";if(const char*h=std::getenv("HOME");h&&*h)return std::filesystem::path(h)/".config/mistercast/config.json";return std::filesystem::current_path()/"config.json";}
static std::string escape(const std::string&s){std::string o;for(char c:s){if(c=='"'||c=='\\')o+='\\';if(c=='\n'){o+="\\n";continue;}o+=c;}return o;}
static bool stringValue(const std::string&s,const char*k,std::string&o){std::regex r(std::string("\\\"")+k+"\\\"\\s*:\\s*\\\"([^\\\"]*)\\\"");std::smatch m;if(!std::regex_search(s,m,r))return false;o=m[1];return true;}
static bool numberValue(const std::string&s,const char*k,double&o){std::regex r(std::string("\\\"")+k+"\\\"\\s*:\\s*(-?[0-9]+(?:\\.[0-9]+)?)");std::smatch m;if(!std::regex_search(s,m,r))return false;try{o=std::stod(m[1]);return true;}catch(...){return false;}}
static bool boolValue(const std::string&s,const char*k,bool&o){std::regex r(std::string("\\\"")+k+"\\\"\\s*:\\s*(true|false)");std::smatch m;if(!std::regex_search(s,m,r))return false;o=m[1]=="true";return true;}
static bool modelineObject(const std::string&s,Modeline&m){double n;stringValue(s,"name",m.name);auto get=[&](const char*k,auto&v){double x;if(!numberValue(s,k,x))return false;v=static_cast<std::decay_t<decltype(v)>>(x);return true;};bool interlace=false;if(!numberValue(s,"pixelClockMHz",n))return false;m.pixelClockMHz=n;if(!get("hActive",m.hActive)||!get("hBegin",m.hBegin)||!get("hEnd",m.hEnd)||!get("hTotal",m.hTotal)||!get("vActive",m.vActive)||!get("vBegin",m.vBegin)||!get("vEnd",m.vEnd)||!get("vTotal",m.vTotal))return false;boolValue(s,"interlaced",interlace);m.interlaced=interlace;return !m.validate();}
AppConfig loadConfig(const std::filesystem::path&p,std::string*w){AppConfig c;std::ifstream f(p);if(!f)return c;std::stringstream b;b<<f.rdbuf();auto s=b.str();double n;
  if(!numberValue(s,"version",n)||n!=1){if(w)*w="invalid or unsupported config; safe defaults loaded";return AppConfig{};}c.version=1;stringValue(s,"target",c.target);stringValue(s,"monitor",c.source.monitor);stringValue(s,"modelineName",c.modeline.name);
  auto num=[&](const char*k,auto&v){double x;if(numberValue(s,k,x))v=static_cast<std::decay_t<decltype(v)>>(x);};num("frameDelay",c.source.frameDelay);num("width",c.source.width);num("height",c.source.height);num("xOffset",c.source.xOffset);num("yOffset",c.source.yOffset);num("pixelClockMHz",c.modeline.pixelClockMHz);num("hActive",c.modeline.hActive);num("hBegin",c.modeline.hBegin);num("hEnd",c.modeline.hEnd);num("hTotal",c.modeline.hTotal);num("vActive",c.modeline.vActive);num("vBegin",c.modeline.vBegin);num("vEnd",c.modeline.vEnd);num("vTotal",c.modeline.vTotal);boolValue(s,"syncRefresh",c.source.syncRefresh);boolValue(s,"audio",c.source.audio);boolValue(s,"preview",c.source.preview);boolValue(s,"interlaced",c.modeline.interlaced);
  std::string x;if(stringValue(s,"alignment",x))parseAlignment(x,c.source.alignment);if(stringValue(s,"crop",x))parseCropMode(x,c.source.crop);if(stringValue(s,"rotation",x))parseRotation(x,c.source.rotation);auto array=s.find("\"customModelines\"");if(array!=std::string::npos){auto begin=s.find('[',array),end=s.find(']',begin);if(begin!=std::string::npos&&end!=std::string::npos){std::regex object("\\{([^{}]*)\\}");for(std::sregex_iterator it(s.begin()+begin,s.begin()+end,object),last;it!=last;++it){Modeline custom;if(modelineObject((*it)[1],custom))c.customModelines.push_back(std::move(custom));}}}if(auto e=c.validate()){if(w)*w="invalid config ("+*e+"); safe defaults loaded";return AppConfig{};}return c;}
bool saveConfig(const AppConfig&c,const std::filesystem::path&p,std::string&e){if(auto x=c.validate()){e=*x;return false;}std::error_code ec;std::filesystem::create_directories(p.parent_path(),ec);if(ec){e=ec.message();return false;}auto tmp=p;tmp+=".tmp."+std::to_string(::getpid());std::ofstream f(tmp,std::ios::trunc);if(!f){e="cannot create temporary configuration";return false;}
 f<<"{\n  \"version\": 1,\n  \"target\": \""<<escape(c.target)<<"\",\n  \"monitor\": \""<<escape(c.source.monitor)<<"\",\n  \"syncRefresh\": "<<(c.source.syncRefresh?"true":"false")<<",\n  \"audio\": "<<(c.source.audio?"true":"false")<<",\n  \"preview\": "<<(c.source.preview?"true":"false")<<",\n  \"frameDelay\": "<<c.source.frameDelay<<",\n  \"alignment\": \""<<toString(c.source.alignment)<<"\",\n  \"crop\": \""<<toString(c.source.crop)<<"\",\n  \"width\": "<<c.source.width<<", \"height\": "<<c.source.height<<",\n  \"xOffset\": "<<c.source.xOffset<<", \"yOffset\": "<<c.source.yOffset<<",\n  \"rotation\": \""<<toString(c.source.rotation)<<"\",\n  \"modelineName\": \""<<escape(c.modeline.name)<<"\",\n  \"pixelClockMHz\": "<<c.modeline.pixelClockMHz<<",\n  \"hActive\": "<<c.modeline.hActive<<", \"hBegin\": "<<c.modeline.hBegin<<", \"hEnd\": "<<c.modeline.hEnd<<", \"hTotal\": "<<c.modeline.hTotal<<",\n  \"vActive\": "<<c.modeline.vActive<<", \"vBegin\": "<<c.modeline.vBegin<<", \"vEnd\": "<<c.modeline.vEnd<<", \"vTotal\": "<<c.modeline.vTotal<<",\n  \"interlaced\": "<<(c.modeline.interlaced?"true":"false")<<",\n  \"customModelines\": [";for(size_t i=0;i<c.customModelines.size();++i){auto&m=c.customModelines[i];if(i)f<<',';f<<"\n    {\"name\":\""<<escape(m.name)<<"\",\"pixelClockMHz\":"<<m.pixelClockMHz<<",\"hActive\":"<<m.hActive<<",\"hBegin\":"<<m.hBegin<<",\"hEnd\":"<<m.hEnd<<",\"hTotal\":"<<m.hTotal<<",\"vActive\":"<<m.vActive<<",\"vBegin\":"<<m.vBegin<<",\"vEnd\":"<<m.vEnd<<",\"vTotal\":"<<m.vTotal<<",\"interlaced\":"<<(m.interlaced?"true":"false")<<'}';}f<<"\n  ]\n}\n";f.flush();if(!f){e="failed writing configuration";f.close();std::filesystem::remove(tmp);return false;}f.close();std::filesystem::rename(tmp,p,ec);if(ec){e=ec.message();std::filesystem::remove(tmp);return false;}return true;}
}
