#include "mistercast/stream_session.hpp"
#include "mistercast/transform.hpp"
#include <chrono>
namespace mistercast {
StreamSession::StreamSession(std::unique_ptr<IVideoCapture>v,std::unique_ptr<IAudioCapture>a):video_(std::move(v)),audio_(std::move(a)){}StreamSession::~StreamSession(){stop();}
SessionStats StreamSession::stats()const{SessionStats result;result.capturedFrames=captured_;result.sentFrames=sent_;result.droppedFrames=dropped_;result.audioDroppedSamples=audioDropped_;result.audioUnderrunSamples=audioUnderrun_;result.audioBufferedSamples=audioRing_.size();auto seconds=std::chrono::duration<double>(std::chrono::steady_clock::now()-startedAt_).count();if(seconds>0){result.captureFps=result.capturedFrames/seconds;result.streamFps=result.sentFrames/seconds;}return result;}
void StreamSession::setState(SessionState s,std::optional<SessionError>e){state_=s;if(callback_)callback_(s,e);}
void StreamSession::fail(SessionError e){stop_=true;setState(SessionState::Error,e);cv_.notify_all();}
bool StreamSession::start(const AppConfig&c,StateCallback cb,std::string*err){if(state_!=SessionState::Idle&&state_!=SessionState::Error){if(err)*err="stream is already active";return false;}stop();callback_=std::move(cb);config_=c;if(auto e=c.validate()){if(err)*err=*e;setState(SessionState::Error,SessionError{"config",*e,"Correct the settings and try again."});return false;}if(c.target.empty()){if(err)*err="target address is required";return false;}stop_=false;dropped_=captured_=sent_=audioDropped_=audioUnderrun_=0;audioRing_.reset();setState(SessionState::Starting);auto onError=[this](SessionError e){fail(std::move(e));};if(!video_->start(c.source.monitor,onError)){if(err)*err="video capture initialization failed";setState(SessionState::Error);return false;}uint32_t rate=48000;if(c.source.audio&&!audio_->start(onError)){video_->stop();if(err)*err="audio capture initialization failed";setState(SessionState::Error);return false;}if(c.source.audio)rate=audio_->sampleRate();std::string e;if(!transport_.open(c.target,rate,e)||!transport_.switchMode(c.modeline,e)){audio_->stop();video_->stop();transport_.close();if(err)*err=e;setState(SessionState::Error,SessionError{"network",e,"Verify the address, MiSTer core, and UDP port 32100."});return false;}startedAt_=std::chrono::steady_clock::now();if(c.source.audio)audioThread_=std::thread(&StreamSession::audioLoop,this);captureThread_=std::thread(&StreamSession::captureLoop,this);renderThread_=std::thread(&StreamSession::renderLoop,this);setState(SessionState::Streaming);return true;}
void StreamSession::stop()noexcept{auto s=state_.load();if(s==SessionState::Idle&&!captureThread_.joinable()&&!renderThread_.joinable()&&!audioThread_.joinable())return;if(s!=SessionState::Error)setState(SessionState::Stopping);stop_=true;cv_.notify_all();video_->stop();audio_->stop();if(captureThread_.joinable()&&captureThread_.get_id()!=std::this_thread::get_id())captureThread_.join();if(renderThread_.joinable()&&renderThread_.get_id()!=std::this_thread::get_id())renderThread_.join();if(audioThread_.joinable()&&audioThread_.get_id()!=std::this_thread::get_id())audioThread_.join();transport_.close();{std::lock_guard<std::mutex>l(mutex_);frames_.clear();}setState(SessionState::Idle);}
void StreamSession::captureLoop(){auto period=std::chrono::duration_cast<std::chrono::steady_clock::duration>(std::chrono::duration<double>(1.0/config_.modeline.refreshHz()));auto deadline=std::chrono::steady_clock::now();auto nextPreview=deadline;while(!stop_){Frame f;if(!video_->next(f,std::chrono::milliseconds(100))){if(!stop_)std::this_thread::sleep_for(std::chrono::milliseconds(5));continue;}++captured_;auto now=std::chrono::steady_clock::now();if(config_.source.preview&&previewCallback_&&now>=nextPreview){previewCallback_(f);nextPreview=now+std::chrono::milliseconds(100);}{std::lock_guard<std::mutex>l(mutex_);if(frames_.size()==3){frames_.pop_front();++dropped_;}frames_.push_back(std::move(f));}cv_.notify_one();deadline+=period;now=std::chrono::steady_clock::now();if(now<deadline)std::this_thread::sleep_until(deadline);else if(now>deadline+period)deadline=now;}}
void StreamSession::renderLoop(){uint32_t number=0;uint8_t field=0;auto period=std::chrono::duration_cast<std::chrono::steady_clock::duration>(std::chrono::duration<double>(1.0/config_.modeline.refreshHz()));std::vector<int16_t>audioSamples;double audioRemainder=0;if(config_.source.audio){audioSamples.reserve(size_t(audio_->sampleRate()*2/config_.modeline.refreshHz())+2);const auto prebufferSamples=audio_->sampleRate()/10;const auto timeout=std::chrono::steady_clock::now()+std::chrono::milliseconds(100);while(!stop_&&audioRing_.size()<prebufferSamples&&std::chrono::steady_clock::now()<timeout)std::this_thread::sleep_for(std::chrono::milliseconds(2));}auto deadline=std::chrono::steady_clock::now();while(!stop_){Frame f;{std::unique_lock<std::mutex>l(mutex_);cv_.wait(l,[&]{return stop_||!frames_.empty();});if(stop_)break;while(frames_.size()>1){frames_.pop_front();++dropped_;}f=std::move(frames_.front());frames_.pop_front();}deadline+=period;auto delay=period*config_.source.frameDelay/10;if(config_.source.frameDelay)std::this_thread::sleep_until(deadline-period+delay);std::vector<uint8_t>rgb;std::string e;if(!transformRgb24(f,config_.source,config_.modeline,field,rgb,e)||!transport_.sendFrame(++number,field,rgb,e)){fail({"stream",e,"Check capture geometry and network connectivity."});break;}++sent_;if(config_.source.audio){audioRemainder+=audio_->sampleRate()*2/config_.modeline.refreshHz();auto count=size_t(audioRemainder);audioRemainder-=count;audioSamples.resize(count);auto real=audioRing_.pop(audioSamples.data(),count);audioUnderrun_+=count-real;if(!transport_.sendAudio(audioSamples.data(),audioSamples.size(),e)){fail({"audio",e,"Check the network and restart streaming."});break;}}if(config_.modeline.interlaced)field^=1;std::this_thread::sleep_until(deadline);auto now=std::chrono::steady_clock::now();if(now>deadline+period)deadline=now;}}
void StreamSession::audioLoop(){while(!stop_){PcmBlock b;if(!audio_->next(b,std::chrono::milliseconds(100))){if(!stop_)std::this_thread::sleep_for(std::chrono::milliseconds(5));continue;}audioDropped_+=audioRing_.push(b.samples.data(),b.samples.size());}}
}
